export const SKIP_ANALYTICS: boolean = true

export const ANALYTICS_EVENT_KEYS = {
    CloudRegionEnter: "gp_region_cloud_visit",
    CloudRegionLeave: "gp_region_cloud_leave",
    BarRegionEnter: "gp_region_bar_visit",
    BarRegionLeave: "gp_region_bar_leave",
    ClassicSliderInteract: "gp_interactible_classSlider_interact",
    CrowdSliderInteract: "gp_interactible_crowdSlider_interact",
    EventsSliderInteract: "gp_interactible_eventsSlider_interact",
    BeerMugsInteract: "gp_interactible_beerMugs_interact",
    PunchingBagInteract: "gp_interactible_punchingBag_interact",
    JukeBoxInteract: "gp_interactible_jukeBox_interact",
    MicrophoneInteract: "gp_interactible_microphone_interact",
    AtariMachineInteract: "gp_interactible_atariMachine_interact",
    AtariMachineStart: "gp_interactible_atariMachine_start",
    AtariMachineEnd: "gp_interactible_atariMachine_end",
    BarTenderInteract: "gp_interactible_barTender_interact",
    BarTenderStart: "gp_interactible_barTender_start",
    BarTenderEnd: "gp_interactible_barTender_end",
    BarLadyInteract: "gp_interactible_barLady_interact",
    BarLadyStart: "gp_interactible_barLady_start",
    BarLadyEnd: "gp_interactible_barLady_end",
    AINPCInteract: "gp_interactible_aiNpc_interact",
    AINPCStart: "gp_interactible_aiNpc_start",
    AINPCEnd: "gp_interactible_aiNpc_end",
    DogeInteract: "gp_interactible_doge_interact",
    DogeStart: "gp_interactible_doge_start",
    DogeEnd: "gp_interactible_doge_end",
    CatGuyInteract: "gp_interactible_catGuy_interact",
    CatGuyStart: "gp_interactible_catGuy_start",
    CatGuyEnd: "gp_interactible_catGuy_end",
}